(
 (module main
   (class Counter (value)
     (method get () (this --> value))
     (method inc ()
       (def v (this --> value))
       (def one 1.0)
       (def zero 0.0)
       (if0 zero
         (block (def newVal (v + one))
                (this --> value = newVal))
         (v = 4.0))
       (this --> value))))
 (timport main (((value Number)) ((get () Number) (inc () Number))))
 (def inter 0.0)
 (def zero 0.0)
 (def c (new Counter (zero)))
 (inter = (c --> inc ()))
 (inter = (c --> inc ()))
 (c --> get ())
 )