(
 (tmodule typed (class check () (method check (o) (o isa check))) ( () ( (check ( ( ((field Number) ) ( (verify () Number) )) ) Number)) ))
 (tmodule typedtwo (import typed) (class A (field) (method verify ()
                                            (def checker (new check ()))
                                            (checker --> check (this))))
          ( ((field Number) ) ( (verify () Number) )))
 (import typedtwo)
 (def four 4.0)
 (def o (new A (four)))
 (o --> verify ())
 )