((tmodule mod (class C () (method mtwo (x) (this = x) 4.0)) ( ()
                                      ( (mtwo  (Number) Number)  )
                                                                   ))
          (import mod)
                     (def ten 10.0)
                                ten)